### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by qingzinai** [baozouai/react-antd-admin-ts#1]
我再git clone 后install了包然后发现
![145D2A62-AF2F-441D-A749-45989B984C8C](https://user-images.githubusercontent.com/34832141/105325230-52496400-5c07-11eb-85c5-03ad9588da4f.png)
然后我猜可能是svg需要单独下载，但是单独下载svg后还是报编译错位请问是我少下载了包吗？

**Comment by baozouai** [comment]
@qingzinai 我启动了没问题，有问题加我wechat: baozouai
